#pragma once

// build stamp, generated by cmake/write_version.cmake into the build tree. the
// fallbacks keep the sources compiling outside the cmake build

#if __has_include(<build_info.h>)
#include <build_info.h>
#endif

#ifndef FIXHOP_BUILD_VERSION
#define FIXHOP_BUILD_VERSION "0.0.0"
#endif

#ifndef FIXHOP_BUILD_COMMIT
#define FIXHOP_BUILD_COMMIT "unknown"
#endif

#ifndef FIXHOP_BUILD_DATE
#define FIXHOP_BUILD_DATE "unknown"
#endif

namespace fixhop
{
    constexpr const char *build_version = FIXHOP_BUILD_VERSION;
    constexpr const char *build_commit = FIXHOP_BUILD_COMMIT;
    constexpr const char *build_date = FIXHOP_BUILD_DATE;

    constexpr const char *repo_url = "https://github.com/speedrun-16/fixhop";
}
